catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home_view, name='home_view'),
    path('books/', views.Book_view.as_view(),name='books'),
    path('books/<int:pk>',views.Book_Detail_View,name='book_detail'),
    path('author/<int:pk>',views.Author_Detail.as_view(), name='author_detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create')
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('',RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('authentication.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models  # Importing the models module from Django for defining database models
from django.db.models import UniqueConstraint  # Importing UniqueConstraint to define unique constraints on model fields
from django.db.models.functions import Lower  # Importing Lower to perform case-insensitive comparisons
from django.urls import reverse  # Importing reverse to generate URLs for model instances
import uuid  # Importing the uuid module for generating unique IDs


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,  # Ensures each genre name is unique
        help_text="Enter the book genre"
    )

    def __str__(self):
        return self.name  # Returns the name of the genre

    def get_absolute_url(self):
        return reverse("genre_detail", args=[str(self.id)])  # Returns the URL to view details of the genre
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),  # Case-insensitive uniqueness constraint on the 'name' field
                name='genre_name_case_insensitive_unique',
                violation_error_message="This Genre already exists.",
            ),
        ]


class Language(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,  # Ensures each language name is unique
        help_text="Enter a language name (e.g., English, French, Japanese)"
    )

    def __str__(self):
        return self.name  # Returns the name of the language

    def get_absolute_url(self):
        return reverse("language_detail", args=[str(self.id)])  # Returns the URL to view details of the language
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),  # Case-insensitive uniqueness constraint on the 'name' field
                name='language_name_case_insensitive_unique',
                violation_error_message="Language already exists.",
            ),
        ]


class Author(models.Model):
    fname = models.CharField('First Name', max_length=100)
    lname = models.CharField('Last Name', max_length=100)
    dob = models.DateField('Date of Birth', null=True, blank=True)
    dod = models.DateField('Date of Death', null=True, blank=True)

    def __str__(self):
        return f"{self.fname} {self.lname}"  # Returns the full name of the author

    def get_absolute_url(self):
        return reverse("author_detail", args=[str(self.id)])  # Returns the URL to view details of the author
    
    class Meta:
        ordering = ['lname', 'fname']  # Specifies the default ordering of authors by last name and first name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT, null=True)  # Defines a many-to-one relationship with Author model
    summary = models.TextField(
        max_length=1000,
        help_text="Enter a brief description of the book",
        null=True
    )
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        unique=True,  # Ensures each ISBN is unique
        help_text="13 character ISBN"
    )
    genre = models.ManyToManyField(
        Genre,
        help_text="Select a genre for this book"
    )
    language = models.ForeignKey(Language, on_delete=models.RESTRICT, null=True)  # Defines a many-to-one relationship with Language model

    def __str__(self):
        return self.title  # Returns the title of the book

    def get_absolute_url(self):
        return reverse("book_detail", args=[str(self.id)])  # Returns the URL to view details of the book


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this transaction")  # Generates a UUID for each BookInstance
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)  # Defines a many-to-one relationship with Book model
    imprint = models.CharField(max_length=200, null=True, blank=True)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        blank=True,
        choices=LOAN_STATUS,
        default='m',
        help_text='Book availability',
    )

    def __str__(self):
        return f"{self.id} ({self.book.title})"  # Returns the ID and title of the book instance

    class Meta:
        ordering = ['due_back']  # Specifies the default ordering of book instances by due back date

catalog/views.py
from django.shortcuts import render, get_object_or_404  # Import render function to render templates and get_object_or_404 to get objects or return 404 error
from django.http import HttpResponse  # Import HttpResponse for sending HTTP responses
from django.template import loader  # Import loader for template loading
from .models import *  # Import all models from the current application
from django.views import generic  # Import generic views for class-based views

from django.shortcuts import get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Define a list of menu items to be used in the navigation menu
menu_items = [
    {'text': 'Home', 'urlName': '/'},  # Home menu item
    {'text': 'All Books', 'urlName': '/catalog/books/'},  # All Books menu item
    {'text': 'All Author', 'urlName': '#'},  # All Author menu item
    {'text': 'Log out', 'urlName': '/accounts/logout/'} 
    ]

class AuthorCreate(LoginRequiredMixin, generic.edit.CreateView):
    login_url = "/account/login"
    redirect_field_name = 'login'
    model = Author
    fields = ['fname', 'lname', 'dob', 'dod']
    initial = {'dob', '05/06/1986'}
    template_name = "author_form.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu-items"] = menu_items
        return context
    
    

@login_required(redirect_field_name='login')

    # return render(request, 'index.html', context=context)

# Define the home view function
def home_view(request):
    num_books = Book.objects.all().count()  # Count all books in the database
    num_instances = BookInstance.objects.all().count()  # Count all book instances in the database

    num_available_bookinstances = BookInstance.objects.filter(status__exact='a').count()  # Count all available book instances (status = 'a')
    num_authors = Author.objects.all().count()  # Count all authors in the database

    # Create context dictionary to pass data to the template
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_available_bookinstances': num_available_bookinstances,
        'num_authors': num_authors,
        'menu_items': menu_items,  # Pass menu items to the template
        'user': request.user
    }

    # Render the index.html template with the context data
    return render(request, 'index.html', context=context)

# Define the Book view class for listing all books
class Book_view(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts/login/'
    redirect_field_name = 'login'
    model = Book  # Specify the model to be used
    context_object_name = 'book_list'  # Name of the context variable for the book list
    # queryset = Book.objects.filter(title__icontains='Positive')[:2]  # Example of filtering queryset (commented out)
    queryset = Book.objects.all()  # Queryset to get all books
    template_name = 'book_list.html'  # Specify the template to be used
    
    # Override get_context_data to add additional context data
    def get_context_data(self, **kwargs):
        context = super(Book_view, self).get_context_data(**kwargs)  # Call the base implementation
        context['menu_items'] = menu_items  # Add menu items to the context
        return context

# Commented out Book_Detail_View class
# class Book_Detail_View(generic.DetailView):
#     model = Book
#     template_name = 'book_detail.html'
#     def get_context_data(self, **kwargs):
#         context = super(Book_Detail_View,self).get_context_data(**kwargs)
#         context['menu_items'] = menu_items
#         return context

# Define the Author detail view class for showing author details
class Author_Detail(generic.DeleteView):
    model = Author  # Specify the model to be used
    template_name = 'author_detail.html'  # Specify the template to be used
    @login_required(redirect_field_name='login')    #to strict the access
    # Override get_context_data to add additional context data
    def get_context_data(self, **kwargs):
        context = super(Author_Detail, self).get_context_data(**kwargs)  # Call the base implementation
        context['menu_items'] = menu_items  # Add menu items to the context
        return context
    
@login_required(redirect_field_name='login')  #if we put it, we can't see any webpage befor login

# Define the Book detail view function
def Book_Detail_View(request, pk):
    book = get_object_or_404(Book, pk=pk)  # Get the book object by primary key or return 404 error
    context = {
        'book': book,  # Add book object to the context
        'menu_items': menu_items  # Add menu items to the context
    }
    # Render the book_detail.html template with the context data
    return render(request, 'book_detail.html', context=context)

catalog/templates/author_detail.html
{% extends "home.html" %}{%block navbar%} {% for menu in menu_items %}
<li class="nav-item">
  <a class="nav-link active" href="{{menu.urlName}}" aria-current="page"
    >{{menu.text}}</a
  >
</li>
{% endfor %} {% endblock navbar %} {% block content %} {{author.fname}}
{%endblock content %}

catalog/templates/author_form.html
{% extends "home.html" %}

{% block navbar %}
{% for menu in menu_items %}
<li class="nav-item">
    <a class="nav-link" href="{{menu.urlName}}" aria-current="page">{{menu.text}}</a>
</li>
{% endfor %}


{% endblock navbar %}
{% block content %}
    <form method="post">
        {%csrf_token%}
        {{form.as_table}}
        <button type="submit">Create</button>
    </form>
{% endblock content %}

catalog/templates/author_list.html
{% extends "home.html" %} {%block navbar%} {% for menu in menu_items %}
<li class="nav-item">
  <a class="nav-link active" href="{{menu.urlName}}" aria-current="page"
    >{{menu.text}}</a
  >
</li>
{% endfor %} {% endblock navbar %} {% block content %} {% if book_list %}
<ul>
  {% for book in book_list %}
  <li>
    <a href="{{book.get_absolute_url}}">{{book.title}}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<h2>No Book to display</h2>
{% endif %} {% endblock content %}

catalog/templates/book_detail.html
{% extends "home.html" %} {%block navbar%} {% for menu in menu_items %}
<li class="nav-item">
  <a class="nav-link active" href="{{menu.urlName}}" aria-current="page"
    >{{menu.text}}</a
  >
</li>
{% endfor %} {% endblock navbar %} {%block content%}
<div class="row justify-content-center align-items-center g-2">
  <div class="col-4"><h4>Title:</h4></div>
  <div class="col-8"><i>{{book.title}}</i></div>
  <div class="col-4"><h4>Summary:</h4></div>
  <div class="col-8"><i>{{book.summary}}</i></div>
  <div class="col-4"><h4>ISBN:</h4></div>
  <div class="col-8"><i>{{book.isbn}}</i></div>
  <div class="col-4"><h4>Author:</h4></div>
  <div class="col-8">
    <i><a href="{{book.author.get_absolute_url}}">{{book.author}}</a></i>
  </div>
  <div class="col-4"><h4>Language:</h4></div>
  <div class="col-8"><i>{{book.language}}</i></div>
  <div class="col-4"><h4>Genre:</h4></div>
  <div class="col-8"><i>{{book.genre.all|join:", "}}</i></div>  
  {% comment %}  {% endcomment %}
</div>

<div class="row justify-content-center align-items-center g-2">
  <div class="col">
    {% for copy in book.bookinstance_set.all %}
    <h2
      class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"
    >
      {{copy.get_status_display}}
    </h2>
    {% if copy.status != 'a' %}
    <h3>Due returned: {{copy.due_back}}</h3>
    {% endif %}
    <p>Instance Code: {{copy.id}}</p>
    {% endfor %}
  </div>
</div>

{%endblock content%}

catalog/templates/book_list.html
{% extends "home.html" %} {%block navbar%} {% for menu in menu_items %}
<li class="nav-item">
  <a class="nav-link active" href="{{menu.urlName}}" aria-current="page"
    >{{menu.text}}</a
  >
</li>
{% endfor %} {% endblock navbar %} {% block content %} {% if book_list %}
<ul>
  {% for book in book_list %}
  <li>
    <a href="{{book.get_absolute_url}}">{{book.title}}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<h2>No Book to display</h2>
{% endif %} {% endblock content %}

catalog/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Local library</title>
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <button
          class="navbar-toggler d-lg-none"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapsibleNavId"
          aria-controls="collapsibleNavId"
          aria-expanded="false"
          aria-label="Toggle navigation"
        ></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav me-auto mt-2 mt-lg-0">
            {% block navbar %} {% endblock navbar %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container-fluid">
        {% block content %} {% endblock content %}
      </div>
    </main>
    <footer>
      <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

catalog/templates/index.html
{% extends "home.html" %} {%block navbar%} {% for menu in menu_items %}
<li class="nav-item">
  <a class="nav-link active" href="{{menu.urlName}}" aria-current="page"
    >{{menu.text}}</a
  >
</li>
{% endfor %} {% endblock navbar %} {% block content %}
<div class="row justify-content-center align-items-center g-2">
  <div class="col-12">
    <h1>Welcome {{user.first_name}} to the localLibrary</h1>
  </div>
  <div class="col-6">
    <ul>
      <li><strong>Number of Books:</strong>{{num_books}}</li>
      <li><strong>Number of Book Instance:</strong>{{num_instances}}</li>
      <li>
        <strong>Number of Available Book Instances:</strong
        >{{num_available_bookinstances}}
      </li>
      <li><strong>Number of Author:</strong>{{num_authors}}</li>
    </ul>
  </div>
  <div class="col">Column</div>
</div>

{% endblock content%}

catalog/templates/navbar.html
{% extends "home.html" %} {%block navbar%}
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
  <button
    class="navbar-toggler d-lg-none"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#collapsibleNavId"
    aria-controls="collapsibleNavId"
    aria-expanded="false"
    aria-label="Toggle navigation"
  ></button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav me-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'index' %}" aria-current="page"
          >Home</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">All Books</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">All Authors</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock navbar %}